version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # App will create its own DB!
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      # Expose on different port to prevent conflict with local
      - '6543:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - "redis_data:/redis/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@project.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    depends_on:
      - db
      - redis
    build: ./services/backend
    working_dir: /backend/app
    restart: always
    ports:
      - '8000:8000'
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONDONTWRITEBYTECODE=1
      - PROJECT_NAME=Project
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=project_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn src.main:app --host=0.0.0.0 --port=8000 --reload --log-level 'debug'

  worker:
    depends_on:
      - db
      - redis
    build: ./services/backend
    working_dir: /backend/app
    restart: always
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONDONTWRITEBYTECODE=1
      - PROJECT_NAME=Project
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=project_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: arq src.modules.arqueue.worker.ArqueueWorkerSettings
    deploy:
      replicas: 1

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
