[package]
name = "rst_tax_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rst_tax_calculator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
postgres = "0.17.2"
