"""Create Login

Revision ID: ad9b83d61dcf
Revises: 829f639ffb10
Create Date: 2024-01-19 13:18:33.957116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9b83d61dcf'
down_revision: Union[str, None] = '8b97a0c567f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('verification_token', sa.UUID(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('verification_token'),
    schema='shared'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login', schema='shared')
    # ### end Alembic commands ###
