"""Create Trade  Model

Revision ID: b8845a588a10
Revises: 829f639ffb10
Create Date: 2023-12-26 10:03:51.572264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8845a588a10'
down_revision: Union[str, None] = '829f639ffb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('mv', sa.Float(), nullable=False),
    sa.Column('q', sa.Float(), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('mv_local', sa.Float(), nullable=False),
    sa.Column('q_local', sa.Float(), nullable=False),
    sa.Column('p_local', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    # ### end Alembic commands ###
